# Generated by Django 5.0.1 on 2024-01-28 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_event_slug_news_slug_volunteer_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
