# Generated by Django 5.0.1 on 2024-01-29 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_event_slug_alter_volunteer_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
