# Generated by Django 3.2.25 on 2024-05-21 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20240521_2252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='investor',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='news',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='slug',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
